# frozen_string_literal: true
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '2.3.4'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'

group :development, :test do
  gem 'foreman'
end
